### ISSUE TITLE
Import unifi_video

### ISSUE THREAD

**Issue by xxxlucaxxx** [yuppity/unifi-video-api#1]
Hi there,

can you help and describe how to setup the correct path?

Is there any module which needs to be installed?

python luca.py 
Traceback (most recent call last):
  File "luca.py", line 2, in <module>
    from unifi_video import UnifiVideoAPI
ImportError: No module named unifi_video

Thanks
Luca

**Comment by EagleOne42** [comment]
You probably just need to add the folder to your path.  You can add this line (edit to match where you pulled this project to) to your bash profile or just run before you run the script.
export PYTHONPATH=~/git_repos/unifi-video-api

**Comment by yuppity** [comment]
@EagleOne42's suggestion should work.

You could also just clone the repo to your project root. Inside your project directory:

```
git clone https://github.com/yuppity/unifi-video-api.git
```

and then either remove the repo and pluck out the `unifi_video` package:

```
mv unifi-video-api/unifi_video . && rm -r unifi-video-api
```

or, alternatively, symlink the package path (assuming you're on *nix):

```
ln -s unifi-video-api/unifi_video .
```

So, to get setup, run either of these two command sequences inside your own project:

```
git clone https://github.com/yuppity/unifi-video-api.git && \
mv unifi-video-api/unifi_video . && rm -r unifi-video-api
```

```
git clone https://github.com/yuppity/unifi-video-api.git && \
ln -s unifi-video-api/unifi_video .
```

@xxxlucaxxx  feel free to open a new issue if you're still having problems.
