### ISSUE TITLE
unifi_video.camera.CameraModelError: Unsupported camera model

### ISSUE THREAD

**Issue by jebbisson** [yuppity/unifi-video-api#10]
After calling `uva = UnifiVideoAPI(` I recieved the following error with my setup:
`unifi_video.camera.CameraModelError: Unsupported camera model`

I set the version ignore flag but I think that is only for the controller and not individual cameras.

After that, I downloaded the source onto my server and did some debugging and it looks like the following code returns true on a few of my models(Line 180 in camera.py):
`not models.get(self.model, None)`

I checked the strings and looked at what models.get returns and it does return an empty object `{}` which then causes this error.
I'm assuming the camera, which is an older UVC camera isn't supposed to return false in this scenario as this camera is on your supported list.

Maybe its an environment issue but I modified `'UVC': {},` in the models list to be 
```
'UVC': {
'features': [
        ]
},
```
which seems to have resolved the issue for me though I only did a little testing as I just started using your library.

Not sure if there is the right fix or not, or what impacts it has on the rest of the api.

Also my System is Ubuntu 18.04.3 LTS and Python 3.6.9 in case this is some kind of environment difference.

Thanks.

**Comment by yuppity** [comment]
Thank you for reporting this. Definitely a bug. I'll tag a new release soon.
