### ISSUE TITLE
Get frames in real time

### ISSUE THREAD

**Issue by javierrodenas** [yuppity/unifi-video-api#11]
Hello,

I want to get frame in a variable without saving the image as cv2.VideoCapture() in OpenCV. 

Which is the function to get it? I've tried with camera.get_frame(), camera.capture()…

Thank you in advance!!!

**Comment by yuppity** [comment]
*unifi_video* has no support for a live feed. If you wanted to use *unifi_video* for this, you'd have to use UniFi Video's snapshot facility, which you can do via the [`snapshot()`](https://unifi-video-api.readthedocs.io/en/latest/modules/camera.html#unifi_video.camera.UnifiVideoCamera.snapshot) call. So you would have to do something along the lines of

```python
import cv2
import numpy as np
import unifi_video as ufv

uva = ufv.UnifiVideoAPI(api_key='your api key', addr='UniFi Video address', port=7080)
camera = uva.get_camera('somecamera')
cv2.namedWindow('test')

while True:
    frame = cv2.imdecode(np.frombuffer(camera.snapshot(True), dtype=np.uint8), -1)
    cv2.imshow('test', frame)
    cv2.waitKey(10)
```

This is hardly in "real time" though and has other drawbacks, starting with the fact that you'd be opening a new TCP connection and sending an HTTP request for each frame. A much better approach would be to log in to the UniFi Video web interface and setup an RTSP endpoint (this can be done in the camera settings) and then passing the RTSP URL to OpenCV's `VideoCapture()`.

**Comment by javierrodenas** [comment]
Thank you it works!!
