### ISSUE TITLE
API constructor doesn't handle unmanaged cameras gracefully

### ISSUE THREAD

**Issue by twoodrow** [yuppity/unifi-video-api#12]
Ends up being a get on a None object when cameras are being added.

I think the fix is pretty straightforward. Are pull requests welcome?

**Comment by yuppity** [comment]
Thanks for reporting!

Yes, PRs are welcome. I'll push a fix for this tomorrow unless I hear something here (or see a PR).

**Comment by twoodrow** [comment]
I am busy at work with a big deadline, so probably wont be able to do that by tomorrow.

It should reproduce by having a single camera unmanaged on your Unifi Video instance. I am using one of the NVRs right now, but will move to a custom instance eventually.

**Comment by twoodrow** [comment]
Also, I really want to thank you for putting this library together.

**Comment by yuppity** [comment]
It doesn't have to be tomorrow, just let me know if you intend to get into it later in the week and I'll hold off.

> Also, I really want to thank you for putting this library together.

Thank you :)

**Comment by yuppity** [comment]
Spent some time looking at this today but failed to replicate.

I tried duplicating your setup of one unmanaged camera (had no managed cameras at the time of testing) and initiating an API object against it. I do have a suspicion that the fact that the camera had previously been managed by the same UniFi Video instance affected my replication attempts (noticed afterwards that the DB still had the camera's details).

@twoodrow, if there's any chance you'll have the time to have a go at this in the near future please let me know. Alternatively, it might be that simply pasting the UniFi Video bootstrap JSON will help solve this, you can get it by GETting `/api/2.0/bootstrap` (you'll want to remove the sensitive bits before pasting).

I'll setup a fresh UniFi Video + camera combo in a few days if I don't hear anything and then give it another shot.

**Comment by yuppity** [comment]
Finally had the time to setup up a fresh UniFi Video instance and managed to replicate this.

This should be sorted out now but I'll have to make some time for looking into how to best handle unmanaged cameras in general; I expect that having unmanaged cameras will expose other related bugs.

Thanks again for reporting this @twoodrow. Let me know if I missed something and I'll reopen this.
