### ISSUE TITLE
List all recordings of one camera

### ISSUE THREAD

**Issue by MaxDev98** [yuppity/unifi-video-api#14]
Is there any chance to filter recordings by camera id?

`for rec in uva.recordings:
  print(rec)
`
prints all recordings of all cameras without mapping to any appropriate camera. Is it possible to only get all recordings e.g. of Camera 'Garage'?

**Comment by yuppity** [comment]
A [recording](https://unifi-video-api.readthedocs.io/en/latest/modules/recording.html#unifi_video.recording.UnifiVideoRecording) has a list of associated camera ID strings (the `camera` attr). Currently, you'll have to resort to filtering the list of associated camera IDs against the camera's "private" `_id` attr.

Something like this should work:

```python
camera = uva.get_camera('Garage')
for rec in (r for r in uva.recordings if camera._id in r.cameras):
    print(rec)
```

**Comment by MaxDev98** [comment]
Thanks! 
So if i get you right, first all recordings will be shown and we filter after one camera in the second step? 
Wouldn't that produce a massive overhead, if you have many recordings and cameras?

So I guess there is no way to filter in the first place?

**Comment by yuppity** [comment]
>So if i get you right, first all recordings will be shown and we filter after one camera in the second step?
>Wouldn't that produce a massive overhead, if you have many recordings and cameras?

Correct. The recording metadata will not only be downloaded but will obviously be also initialized into `UnifiVideoRecording`s. By default, the number of recordings is capped at 300 and you have to call [`UnifiVideoAPI.refresh_recordings`](https://unifi-video-api.readthedocs.io/en/latest/modules/api.html#unifi_video.api.UnifiVideoAPI.refresh_recordings) manually to fetch more than that.

> So I guess there is no way to filter in the first place?

Yes, _unifi_video_ lacks the logic to filter at the API endpoint. This is an oversight, not a design choice, and I haven't had to pay any attention to it till now; I'll try to make some time and write this in over the weekend. (I'll reference the issue when I've done so, there should be a new release on PyPI shortly after.)

In the meantime, if you want to download footage from a specific camera and you want to avoid the extra bandwidth and RAM usage, then you could look into [`UnifiVideoCamera.recording_between`](https://unifi-video-api.readthedocs.io/en/latest/modules/camera.html#unifi_video.camera.UnifiVideoCamera.recording_between). If you need the functionality of `UnifiVideoRecording` (delete, download, snapshot) then you need to do something along the lines of 

```python
from unifi_video import UnifiVideoAPI
from unifi_video.recording import UnifiVideoRecording

uva = UnifiVideoAPI(...)

def get_camera_recordings(uva, camera, limit=0):
    url = 'recording?idsOnly=false&sortBy=startTime&sort=desc' \
        '&limit={}&cameras[]={}'.format(limit, camera._id)
    return (UnifiVideoRecording(uva, recdata) \
        for recdata in uva.get(url).get('data', []))

for recording in get_camera_recordings(uva, uva.get_camera('Garage'), limit=100):
    print(recording)
```

**Comment by yuppity** [comment]
Sorry it took this long, kept postponing for wanting to sort out some of the time related functionality before reworking the rec fetching. The current release should allow you to replace the code in the last example with

```python
from unifi_video import UnifiVideoAPI

uva = UnifiVideoAPI(...)

for recording in uva.get_recordings(camera=uva.get_camera('Garage')):
    print(recording)
```

See [`get_recordings()` docs](https://unifi-video-api.readthedocs.io/en/latest/modules/api.html#unifi_video.api.UnifiVideoAPI.get_recordings) for more.
