### ISSUE TITLE
3.10.11 Unsupported Unifi Video Version

### ISSUE THREAD

**Issue by jresende7** [yuppity/unifi-video-api#15]
Hello. 

I just upgraded to 3.10.11 and get the error on the command 

`uva = UnifiVideoAPI(api_key='your API', addr='your IP')`

Isn't supported ?

**Comment by yuppity** [comment]
Could you please check which version of *unifi_video* you're using?

Anything before v0.1.7 will throw against UniFi Video 3.10.11. (You should still be able to run it by passing `check_ufv_version=False` to `UnifiVideoAPI` of course.)

**Comment by jresende7** [comment]
That was the problem ... I feel a little embarrassed at the moment! :) I upgraded to version 3.10.11 but did not update _unifi_video_

Thank you for everything again !

**Comment by yuppity** [comment]
No worries :)
