### ISSUE TITLE
UVC G3 micro - motion sensor

### ISSUE THREAD

**Issue by bkupidura** [yuppity/unifi-video-api#16]
Hey,
I plan to buy some G3 micro cams for home-automation. `unifi-video-api` is best lib for unifi i was able to find, but it still lack of basic feature for IOT/automation scenarios.

Is there a way to get information if camera detected motion?

Probably can help with implementation, but before i will buy G3 - want to know if this is even possible? NVR is exposing in any way this information?

**Comment by yuppity** [comment]
If you wanted to use the API you would have to check the recordings and see if there are any new motion recordings and whether or not they are in-progress. You can do this with *unifi-video-api* but you would have to do it by polling the API (which will be a tiny bit less horrible once I'm done with #14).

As far as I know, the API does not provide you with any other way to achieve what you're after. If you'll find it does then please let me know as I'd likely be interested in supporting it in *unifi-video-api*.

Assuming you want to react to motion events, and you want to avoid having to ask the API for new recordings each second or so, then my suggestion would be to take advantage of UniFi Video's email notifications. This is exactly what I'm doing myself to get object detection and to filter out false positives etc.

**Comment by bkupidura** [comment]
Thanks. Yeah polling is not best idea (still better than nothig). But as you suggested i can use some `mail to smth` proxy. Ex. node-red-contrib-mailin-smtp

Probably will go with one G3 micro just to verify what is possible. If i find anything useful, for sure will create MR.

**Comment by yuppity** [comment]
Forgot to mention https://github.com/yuppity/ufv-alerts. I've since worked on it a bit more for my own purposes and none of that work has made it to Github but the core idea hasn't really changed. Should get you started at least.

**Comment by bkupidura** [comment]
Oh, looks good :) For sure will check that 👍
