### ISSUE TITLE
Update supported versions list to include '3.10.13'

### ISSUE THREAD

**Issue by mrichmon** [yuppity/unifi-video-api#19]
unifi-video version 3.10.13 appears to be working with this api code.

I have used the following methods repeatedly with Unifi-Video v3.10.13:
* recording.py -  UnifiVideoRecording::delete
* recording.py -  UnifiVideoRecording::download
* recording.py -  UnifiVideoRecording::delete
* api.py - UnifiVideoAPI::refresh_cameras()
* api.py - UnifiVideoAPI::refresh_recordings()
* camera.py - UnifiVideoCamera::recording_between()
* camera.py - UnifiVideoCamera::get_recording_settings()

All of these methods functioned as expected.

**Comment by yuppity** [comment]
Thank you for the method listing!

Just upgraded my own UniFi Video instance and I'll still need to test some of the other API calls and have a look at the frontend JS. If past UniFi Video updates are of any indication, expanding the supported version range is indeed all that is needed and I'll get to upload a new release to PyPI by tomorrow.

**Comment by mrichmon** [comment]
I am working on automating a camera configuration check. This will possibly lead to automating camera configuration rather than just validating configuration. I'll update when I get more coverage of the api.
