### ISSUE TITLE
Filter by motion or full time recording

### ISSUE THREAD

**Issue by EddieDee** [yuppity/unifi-video-api#20]
Is there a way to filter by type of recording?

**Comment by yuppity** [comment]
With the current PyPI release, you'll have to check [`UnifiVideoRecording.rec_type`](https://unifi-video-api.readthedocs.io/en/latest/modules/recording.html) in your application code:

```python
from unifi_video import UnifiVideoAPI

# types: motionRecording, fullTimeRecording
wanted_type = 'motionRecording'

uva = UnifiVideoAPI(...)

for recording in (rec for rec in uva.recordings if rec.rec_type == wanted_type):
    print(recording)

```

If you're on `master`, then you use [`UnifiVideoAPI.get_recordings()`](https://github.com/yuppity/unifi-video-api/blob/347a56622b107188c356ebe698be0d523d9450fc/unifi_video/api.py#L358-L389):

```python
from unifi_video import UnifiVideoAPI

uva = UnifiVideoAPI(...)

# motion, fulltime or all
for recording in uva.get_recordings('motion'):
    print(recording)
```

There will likely be a new PyPI release soon that will include `UnifiVideoAPI.get_recordings()`; I'd like `get_recordings()` to accept start and end times as well but I want to first sort out how to best handle UTC offsets so that *unifi_video* can determine the correct timezone for all UniFi Video versions (on earlier versions, `bootstrap.json` only has the server's tz db name, no actual offset).

**Comment by EddieDee** [comment]
AWESOME! thanks, this will help me a lot to automate some download from certain cameras and schedules.

About time selection; can I pass time range as URL, because I can get the Url from developer console:
recording?startTime=1599364800000&endTime=1599451200000&idsOnly=true&sortBy=startTime&sort=desc&startTimeRangeMin=-1&startTimeRangeMax=-1

**Comment by yuppity** [comment]
You cannot pass the URL as such, but you can combine some of the `UnifiVideoAPI` methods to help you send your customized HTTP request.

Using the latest PyPI release:

```python
from unifi_video import UnifiVideoAPI
from unifi_video.api import endpoints
from unifi_video.recording import UnifiVideoRecording

uva = UnifiVideoAPI(...)

start_time = 1599364800000
end_time = 1599451200000
recording_count = 100

for recording_metadata in uva.get('{}&startTime={}&endTime={}'.format(
        endpoints['recordings'](recording_count),
        start_time,
        end_time))['data']:
    recording = UnifiVideoRecording(uva, recording_metadata)
    print(recording)
```

If you end up writing the whole URL yourself (ie, not using `endpoints`) then note that you want the `idsOnly` URL param set to `false`, otherwise there is no data to initialize `UnifiVideoRecordings` from. 

If you're on `master`, you can make it a little tidier:

```python
from unifi_video import UnifiVideoAPI
from unifi_video.recording import UnifiVideoRecording

uva = UnifiVideoAPI(...)

url_params = {
    'sortBy': 'startTime',
    'order': 'desc',
    'idsOnly': False,
    'limit': 100,
    'cause': ('motionRecording', 'fullTimeRecording'),
    'startTime': 1599364800000,
    'endTime': 1599451200000,
}

for recording in (UnifiVideoRecording(uva, rec)
        for rec in uva.get('recording', url_params)['data']):
    print(recording)
```

**Comment by EddieDee** [comment]
👍 

I am using latest PyPi release and also on master but I gotta say I really like the way it looks on master; how can you make that loop for a specific camera:

I was using something like: uva.get_camera('1st - Cashiers')

**Comment by yuppity** [comment]
You want to ensure `url_params['cameras']` and `url_params['cause']` are both either a `list` or `tuple`. This should work:

```python
url_params = {
    'cause': ['fullTimeRecording'],
    'startTime': 1598846400000,
    'endTime': 1599364800000,
    'cameras': [uva.get_camera('1st - Cashiers')],
    'sortBy': 'startTime',
    'order': 'desc',
    'idsOnly': False,
    'limit': 100000
}
```

**Comment by EddieDee** [comment]
Still no luck :(, does not filter by fullTimeRecording, even though API is like that:

https://192.168.10.235:7443/api/2.0/recording?cause%5B%5D=fullTimeRecording&startTime=1598846400000&endTime=1599364800000&cameras%5B%5D=58b9f790bbe754ca195c2499&idsOnly=true&sortBy=startTime&sort=desc&startTimeRangeMin=-1&startTimeRangeMax=-1

**Comment by yuppity** [comment]
Ah, an oversight on my part: in the earlier `master` examples, `url_params` should always be a keyword argument when passed to `uva.get()`. So, instead of

```python
uva.get('recording', url_params)
```

be sure to do 

```python
uva.get('recording', url_params=url_params)
```
instead.

Sorry about that.

**Comment by EddieDee** [comment]
perfect, i finally got it to work with this:


`url_params = {
    'cause': ['fullTimeRecording'],
    'startTime': 1599451200000,
    'endTime': 1599537600000,
    'cameras': [uva.get_camera('1st - Cashiers')],
    'sortBy': 'startTime',
    'order': 'desc',
    'idsOnly': False,
    'limit': 1000
}

for recording in (UnifiVideoRecording(uva, rec) for rec in uva.get('recording', url_params=url_params)['data']):
    print(recording)
'+recording.end_time.strftime("%H:%M:%S"))
    recording.download('1st - Cashiers - '+recording.start_time.strftime("%Y-%m-%d, %H-%M-%S")+'-'+recording.end_time.strftime("%H-%M-%S")+'.mp4')
    `

So I just have to get my time coordinates each day and download :D, hopefully we get time selection but in the meantime this saves A LOT of time for me, big THANKS man...

**Comment by yuppity** [comment]
Latest release now has `get_recordings()`. You should be able to run

```python
from unifi_video import UnifiVideoAPI
from datetime import datetime

recognized_rec_types = ('all', 'motion', 'fulltime')

uva = UnifiVideoAPI(...)

for recording in uva.get_recordings(
        recognized_rec_types[0],
        start_time=datetime(2020, 10, 19, 19),
        end_time=datetime(2020, 10, 19, 19)):
    print(recording)
```

See the [docs for `get_recording()`](https://unifi-video-api.readthedocs.io/en/latest/modules/api.html#unifi_video.api.UnifiVideoAPI.get_recordings) for full param list.
