### ISSUE TITLE
UnifiVideoAPI.cameras includes cameras that are not managed by the system

### ISSUE THREAD

**Issue by mrichmon** [yuppity/unifi-video-api#22]
Running the code:
`
self._uva = UnifiVideoAPI(api_key=api_key, addr=unifi_address, check_ufv_version=check_ufv_version)
print(f'raw cameras: {[str(c) for c in self._uva.cameras]}')
`
Produces as output:
`
raw cameras: ["UnifiVideoCamera: {'model': 'UVC G3 Flex', 'name': 'testXcameraX1', 'platform': 'GEN3L'}", "UnifiVideoCamera: {'model': 'UVC G3 Pro', 'name': 'UVC-G3-Pro', 'platform': 'GEN3L'}", "UnifiVideoCamera: {'model': 'UVC G3 Pro', 'name': 'Camera4', 'platform': 'GEN3L'}", "UnifiVideoCamera: {'model': 'UVC G3 Pro', 'name': 'Camera3', 'platform': 'GEN3L'}", "UnifiVideoCamera: {'model': 'UVC G3 Pro', 'name': 'Camera2', 'platform': 'GEN3L'}", "UnifiVideoCamera: {'model': 'UVC G3 Pro', 'name': 'Camera1', 'platform': 'GEN3L'}"]
`

That structure lists 6 cameras.

However, this system only has 4 cameras on the local network and all 4 cameras are named "Camera1", "Camera2", "Camera3", "Camera4".

The other two cameras in the are:
* "testXcameraX1" a camera that was once connected to this instance of Unifi Video NVR. The database may have been reset via the GUI after this camera was moved to a different nework.
* "UVC-G3-Pro" is one of the 4 managed cameras from before I changed the names.

This result may suggest that the unifi-video-api call for get_cameras needs additional filtering to remove unmanaged cameras.

**Comment by yuppity** [comment]
I fear there might be a user or two that have gotten use to the fact that `UnifiVideoAPI.cameras` includes every camera a UniFi Video instance is aware of. I opted for keeping a second collection for cameras that are both managed and connected: `UnifiVideoAPI.active_cameras`.

Please let me know if you think I missed something. I'll keep this open until there's a PyPI release that includes fab93f5.

**Comment by mrichmon** [comment]
That makes sense. I hadn't read into the code in detail. I assumed reading the examples that "cameras" mapped to "managed cameras in the NVR.

A few suggestions:
* Update doc comment on UnifiVideoAPI to include active_cameras in list of attributes.
* The booleans on the cameras are useful.
* A collection of "managed_cameras" might be useful to maintain on the UnifiVideo API object.
* Update the example in README.md to use active_cameras. (Or just add a comment there that explains that "cameras" contains all cameras ever seen by the NVR.

For my use, I am implementing two utilities.
1. a tool that downloads all recordings from the NVR matching certain time criteria and removes the recordings from the NVR.
2. a utility that checks that the camera settings for all cameras match expected settings for my deployments.

In the context of these utilities:
* it is useful to compare whether all managed cameras are active. If not, raise a notification. Looks like I can achieve this with the new booleans.
* it is useful to identify unmanaged cameras to raise a notification that system setup may not have been completed.

If you have access to the last time a camera was connected, that may be useful to include in the camera object. This way, if a camera is not active a developer could choose to only take action on the camera if the disconnect has exceeded some time-window.

**Comment by yuppity** [comment]
Great suggestions, thanks.

Shortly after pushing fab93f5, it occured to me that refresh_cameras() now needs some logic to ensure it doesn't leave any stale cameras in `active_cameras`. I'll give `managed_cameras` more thought when I sort out the potential for stales. 

Re the last connected timestamp, looks like UniFi Video does include it in the output for the `/api/2.0/camera` endpoint, for 3.10.13 at least. I'll assign it to `UnifiVideoCamera.last_seen`.

For reference, here's the full JSON for [`/api/2.0/camera`](https://gist.github.com/yuppity/a70258ac5b48db80f9d509c024b80844) (3.10.13).

**Comment by mrichmon** [comment]
Nice.

**Comment by yuppity** [comment]
Finally managed to release a new version (should be in PyPI too). Here's hoping I didn't forget anything.
