### ISSUE TITLE
Scripting: Download full-time recordings where at least one motion recording was made

### ISSUE THREAD

**Issue by EddieDee** [yuppity/unifi-video-api#23]
I know this might be more scripting related, but I've playing around and right now I have TBs of video but most of them are "static images on video" ( no movement whatsoever) so I was wondering if there a way to only download the full-time videos where there has been at least one motion recording for that time period.

Let's say we have 3 full-time recording videos:
1. 8:00AM to 8:10AM
2. 8:11AM-8:20AM
3. 8:21AM-8:30AM

If there is a motion recording in the 3rd time period I will only download that video.

The other way around is to locked those videos and then filter through it... but let see which ideas might come to you :D

**Comment by yuppity** [comment]
Yes, this does sound like something that should be handled on the application side, i.e. I don't think it makes sense to include anything specific to this in *unifi_video*.

To address the question outright, I would simply get the start times for motion recordings and then fetch fulltime recordings and only act on those that that span over any of the motion recordings:

```python
from unifi_video import UnifiVideoAPI
from datetime import datetime

def fulltime_recs_with_motion(uva, since=None):
    '''Get full time recordings that span one or more motion recordings
    '''

    motion_start_times = [
        r.start_time for r in uva.get_recordings(
            'motion', start_time=since)]

    for fulltime_rec in (uva.get_recordings('fulltime', start_time=since)):
        if [m_start_time for m_start_time in motion_start_times
                if m_start_time >= fulltime_rec.start_time \
                    and m_start_time <= fulltime_rec.end_time]:
            yield fulltime_rec

uva = UnifiVideoAPI(...)

for ft_rec in fulltime_recs_with_motion(uva, datetime(2020, 9, 1)):
    print(ft_rec)
```

(The above is for `master`. Still no PyPI release that includes `get_recordings()`.)

Personally though, I would just download the motion recordings :) Maybe with a minute or two of margin using [`UnifiVideoCamera.recording_between()`](https://unifi-video-api.readthedocs.io/en/latest/modules/camera.html#unifi_video.camera.UnifiVideoCamera.recording_between) if I was worried about something getting left out.

**Comment by mrichmon** [comment]
I'm dealing with this in a different way. I only enable motion-recording on the NVR, and then filter the recordings list to remove overlapping videos.

**Comment by yuppity** [comment]
I'm assuming you got this sorted out @EddieDee. If not, leave a comment.
