### ISSUE TITLE
Host IP Address?

### ISSUE THREAD

**Issue by onezero1010101** [yuppity/unifi-video-api#27]
Do you have an option for the camera IP or HOST?  I see the mac address, and am wanting to poll for devices that are stuck managing, and be able to reboot them via script if they get hung.  I have found everything I need so far for this, except do not see a way to pull the HOST IP.  Thanks

**Comment by yuppity** [comment]
At the moment, no. I have no objections to adding this whenever I push the next minor/patch update though.

Until then, you should get by on

```python
from unifi_video import UnifiVideoAPI

UnifiVideoAPI(...).get_camera('Itään')._data['host']
```

but please don't consider accessing `UnifiVideoCamera._data` as more than a temporary solution.
