### ISSUE TITLE
Does this support Unifi Protect?

### ISSUE THREAD

**Issue by aidenmitchell** [yuppity/unifi-video-api#28]
I need a way to pull a frame from my Protect camera using Python, and this seems great, but I'm not sure if this support Unifi Protect.

**Comment by yuppity** [comment]
Afraid not. _unifi-video-api_ is for UniFi Video only and any compatibility with UniFi Protect is completely coincidental and accidental, and I'd be very surprised if there were any.

You've probably seen these already but this is what I came across:

* https://github.com/briis/pyunifiprotect
* https://github.com/unifi-toolbox/unifi-protect-video-downloader
* https://github.com/hjdhjd/homebridge-unifi-protect
* https://github.com/briis/unifiprotect

Most of them seem to be Homebridge or Home Assistant integrations but I'm sure they can be repurposed for other use cases.

Good luck!
