### ISSUE TITLE
PyPI package

### ISSUE THREAD

**Issue by Diaoul** [yuppity/unifi-video-api#4]
Congratulations on the awesome job :sunglasses: 

This library is exactly what I need to build a component for [Home Assistant](https://www.home-assistant.io/) to display my cameras in my home automation dashboard and that doesn't require access to anything else than the Unifi Video instance (compared to the current [uvc](https://www.home-assistant.io/integrations/uvc/) integration that requires access to individual cameras).

Can you publish this on PyPI? This is a [requirement](https://developers.home-assistant.io/docs/en/creating_component_code_review.html#1-requirements).

Thanks!

**Comment by yuppity** [comment]
PyPI release shouldn't be a problem, assuming I haven't misunderstood what's involved. I'll try to get to it sometime in the coming week.

**Comment by yuppity** [comment]
Should be up now (under the name *unifi-video*). I'll keep this open for now because I'm sure I managed to screw something up; please let me know when you've had time to try it.

**Comment by Diaoul** [comment]
Works great! Nice job. :star2:
